components:
  schemas:
    Service:
      type: object
      properties:
        service_code:
          type: string
          description: The service_code of the services
          example: 'PLN'
        service_name:
          type: string
          description: The service_name of the services
          example: 'Listrik'
        service_icon:
          type: string
          description: The service_icon of the services
          example: 'https://nutech-integrasi.app/dummy.jpg'
        service_tariff:
          type: integer
          description: The nominal service_tarif of the services
          example: 4000
paths:
  /api/services:
    get:
      summary: Get all service
      description: Get all service from the database
      tags: [Services]
      responses:
        200:
          description: A list of service
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Service'
        404:
          description: Services not found
